development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: set_online_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"] %>
  channel_prefix: set_online_production
